baseURL = "https://gohugo.io"
title = "Theme GoldExperience"
aginate = 3
languageCode = "ja"
DefaultContentLanguage = "ja"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]
theme = "GoldExperience"

[outputs]
  home = ["html", "rss", "json"]

[author]
  name = "pop-ketle"
  location = "Japan"

[menu]
  [[menu.icon]]
    name = "twitter"
    url = "https://twitter.com/ken7272popqjim"
    weight = 1

  [[menu.icon]]
    name = "kaggle"
    url = "https://www.kaggle.com/popketle"
    weight = 2

  [[menu.icon]]
    name = "github"
    url = "https://github.com/pop-ketle"
    weight = 3
    
  [[menu.icon]]
    name = "blog"
    url = "https://pop-ketle.hatenablog.com/"
    weight = 4

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

[params]
  [params.github_acount]
    name = "pop-ketle"

  [params.shortcuts]
    [params.shortcuts.0]
      shortcuts_tag = '<i class="fab fa-twitter fa-fw icon_black faa-tada animated-hover"></i>'
      url = 'https://twitter.com/ken7272popqjim'

    [params.shortcuts.1]
      shortcuts_tag = '<i class="fab fa-kaggle fa-fw icon_black faa-tada animated-hover"></i>'
      url = 'https://www.kaggle.com/popketle'

    [params.shortcuts.2]
      shortcuts_tag = '<i class="fab fa-github fa-fw icon_black faa-tada animated-hover"></i>'
      url = 'https://github.com/pop-ketle'
      
    [params.shortcuts.3]
      shortcuts_tag = '<i class="fas fa-blog fa-fw icon_black faa-tada animated-hover"></i>'
      url = 'https://pop-ketle.hatenablog.com/'